[package]
name = "poe"
version = "0.1.0-dev"
authors = ["Alex Crawford <alex@acrawford.com>"]

[dependencies.cortex-m]
version = "*"

[dependencies.cortex-m-semihosting]
version = "*"

[dependencies.efm32gg11b820]
version = "*"
features = [ "rt" ]

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp"
default-features = false
features = [ "proto-ipv4", "socket-tcp" ]

[profile.dev]
incremental = false
opt-level = 3
lto = true

[profile.release]
lto = true
