[package]
name = "poe"
version = "0.1.0-dev"
authors = ["Alex Crawford <alex@acrawford.com>"]

[dependencies]
cortex-m = "*"
efm32gg11b820 = { version = "^0.2.0", features = [ "rt" ] }

[profile.release]
lto = true
