[package]
name = "poe"
version = "0.1.0-dev"
authors = ["Alex Crawford <alex@acrawford.com>"]

[dependencies.cortex-m]
version = "*"

[dependencies.efm32gg11b820]
version = "*"
features = [ "rt" ]

[profile.dev]
incremental = false
opt-level = 3
lto = true

[profile.release]
lto = true
